import type {
  MovieDetailsProps,
  MovieListResponseProps,
  MovieProps,
} from "@/types/tmdb";

export const mockMovie: MovieProps = {
  adult: false,
  backdrop_path: "/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
  genre_ids: [10751, 35, 878],
  id: 552524,
  original_language: "en",
  original_title: "Lilo & Stitch",
  overview:
    "The wildly funny and touching story of a lonely Hawaiian girl and the fugitive alien who helps to mend her broken family.",
  popularity: 768.0749,
  poster_path: "/mKKqV23MQ0uakJS8OCE2TfV5jNS.jpg",
  release_date: "2025-05-17",
  title: "Lilo & Stitch",
  video: false,
  vote_average: 7.1,
  vote_count: 290,
};

export const searchMockMovie: MovieProps = {
  adult: false,
  backdrop_path: "/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg",
  genre_ids: [27, 9648],
  id: 574475,
  original_language: "en",
  original_title: "Final Destination Bloodlines",
  overview:
    "Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.",
  popularity: 423.5113,
  poster_path: "/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg",
  release_date: "2025-05-14",
  title: "Final Destination Bloodlines",
  video: false,
  vote_average: 7.036,
  vote_count: 481,
};

export const mockMovieListResponse: MovieListResponseProps<MovieProps> = {
  page: 1,
  results: [mockMovie],
  total_pages: 100,
  total_results: 2000,
};

export const mockMovieDetails: MovieDetailsProps = {
  ...mockMovie,
  belongs_to_collection: {
    id: 97461,
    name: "Lilo & Stitch Collection",
    poster_path: "/bstyyXaLinnYwoyvo5HaDceJN07.jpg",
    backdrop_path: "/2bQIDuinsMUXjcBZq8hbyPxjhvz.jpg",
  },
  budget: 100000000,
  genres: [
    {
      id: 10751,
      name: "Family",
    },
    {
      id: 35,
      name: "Comedy",
    },
    {
      id: 878,
      name: "Science Fiction",
    },
  ],
  homepage: "https://movies.disney.com/lilo-and-stitch-2025",
  imdb_id: "tt11655566",
  origin_country: ["US"],
  production_companies: [
    {
      id: 2,
      logo_path: "/wdrCwmRnLFJhEoH8GSfymY85KHT.png",
      name: "Walt Disney Pictures",
      origin_country: "US",
    },
    {
      id: 118854,
      logo_path: "/g9LPNlQFoDcHjfnvrEqFmeIaDrZ.png",
      name: "Rideback",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  revenue: 421400000,
  runtime: 108,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Released",
  tagline: "Hold on to your coconuts.",
};

export const mockCredits = {
  id: 552524,
  cast: [
    {
      adult: false,
      gender: 1,
      id: 3988423,
      known_for_department: "Acting",
      name: "Maia Kealoha",
      original_name: "Maia Kealoha",
      popularity: 5.6058,
      profile_path: "/jqsKbBF28V2Oq5tKPR5USkNufwC.jpg",
      cast_id: 23,
      character: "Lilo",
      credit_id: "6427499dc0442901e816b6bf",
      order: 0,
    },
    {
      adult: false,
      gender: 1,
      id: 3025125,
      known_for_department: "Acting",
      name: "Sydney Agudong",
      original_name: "Sydney Agudong",
      popularity: 11.284,
      profile_path: "/3K5hJ3meeClHWsPKetqd9qgyveJ.jpg",
      cast_id: 25,
      character: "Nani",
      credit_id: "64389e8387f3f2009608623c",
      order: 1,
    },
    {
      adult: false,
      gender: 2,
      id: 66193,
      known_for_department: "Directing",
      name: "Chris Sanders",
      original_name: "Chris Sanders",
      popularity: 5.2782,
      profile_path: "/6CtrIOCxggJ5eIAWeFQqd4Hs9FP.jpg",
      cast_id: 18,
      character: "Stitch (voice)",
      credit_id: "6388a71c2e0697024d2c76d8",
      order: 2,
    },
    {
      adult: false,
      gender: 2,
      id: 58225,
      known_for_department: "Acting",
      name: "Zach Galifianakis",
      original_name: "Zach Galifianakis",
      popularity: 9.2428,
      profile_path: "/qsDfoUlRnXHUiqZeBPWHzmgmKGX.jpg",
      cast_id: 19,
      character: "Jumba",
      credit_id: "63f0001ba24c5000d4e2ce42",
      order: 3,
    },
    {
      adult: false,
      gender: 2,
      id: 141034,
      known_for_department: "Acting",
      name: "Billy Magnussen",
      original_name: "Billy Magnussen",
      popularity: 8.4254,
      profile_path: "/ugyx7Wn2uAWsNlR5eX4yWFsGV2Y.jpg",
      cast_id: 24,
      character: "Pleakley",
      credit_id: "6438089c1d53860097252c35",
      order: 4,
    },
    {
      adult: false,
      gender: 2,
      id: 24047,
      known_for_department: "Acting",
      name: "Courtney B. Vance",
      original_name: "Courtney B. Vance",
      popularity: 4.4892,
      profile_path: "/6ci3wf6oecjz875QRwryOsapW0Y.jpg",
      cast_id: 27,
      character: "Cobra Bubbles",
      credit_id: "644028617e403d053425b079",
      order: 5,
    },
    {
      adult: false,
      gender: 1,
      id: 59401,
      known_for_department: "Acting",
      name: "Amy Hill",
      original_name: "Amy Hill",
      popularity: 4.8969,
      profile_path: "/x5vR2MXZiWGHkppRXlXYj7y7611.jpg",
      cast_id: 30,
      character: "Tūtū",
      credit_id: "6443087dcee2f60475363106",
      order: 6,
    },
    {
      adult: false,
      gender: 1,
      id: 13445,
      known_for_department: "Acting",
      name: "Tia Carrere",
      original_name: "Tia Carrere",
      popularity: 6.4583,
      profile_path: "/rnHioNQkSmBAMgEBseu9bu6vw9l.jpg",
      cast_id: 29,
      character: "Mrs. Kekoa",
      credit_id: "6443086f651fcf045e9cc691",
      order: 7,
    },
    {
      adult: false,
      gender: 2,
      id: 4022587,
      known_for_department: "Acting",
      name: "Kaipo Dudoit",
      original_name: "Kaipo Dudoit",
      popularity: 2.2207,
      profile_path: "/5U20b5I3gTKAK5nN3VeWxlXDu6W.jpg",
      cast_id: 28,
      character: "David",
      credit_id: "6443084dfcec2e04bdd9b85f",
      order: 8,
    },
    {
      adult: false,
      gender: 1,
      id: 1278487,
      known_for_department: "Acting",
      name: "Hannah Waddingham",
      original_name: "Hannah Waddingham",
      popularity: 7.5291,
      profile_path: "/eHAICyhvjiRZCgzKyJCk9hWnnjr.jpg",
      cast_id: 39,
      character: "Grand Councilwoman (voice)",
      credit_id: "66b725b4d955793cd207367c",
      order: 9,
    },
    {
      adult: false,
      gender: 2,
      id: 58319,
      known_for_department: "Acting",
      name: "Jason Scott Lee",
      original_name: "Jason Scott Lee",
      popularity: 4.2458,
      profile_path: "/7jObZCM3diuPV0WlKkzOd4uE2CJ.jpg",
      cast_id: 40,
      character: "Lū'au Manager",
      credit_id: "66be7a76c54626f461e61bca",
      order: 10,
    },
    {
      adult: false,
      gender: 1,
      id: 1997286,
      known_for_department: "Acting",
      name: "Celia Kenney",
      original_name: "Celia Kenney",
      popularity: 0.3898,
      profile_path: "/4e8bi7QBgUAJbQzO4SoX7DtHIRS.jpg",
      cast_id: 97,
      character: "AJ",
      credit_id: "681c1b5bd1f4d5422c93abe2",
      order: 11,
    },
    {
      adult: false,
      gender: 0,
      id: 2738916,
      known_for_department: "Acting",
      name: "Brutus LaBenz",
      original_name: "Brutus LaBenz",
      popularity: 0.0866,
      profile_path: "/hmfmb3LBgkAVagBmBWOzS8JYVTt.jpg",
      cast_id: 113,
      character: "Kumu Hula",
      credit_id: "682b9b8117f4b9cfc8db2ebf",
      order: 12,
    },
    {
      adult: false,
      gender: 2,
      id: 1670808,
      known_for_department: "Acting",
      name: "Skyler Bible",
      original_name: "Skyler Bible",
      popularity: 0.9636,
      profile_path: "/lJmkLcOhM12H2cvZCwravA5rIt7.jpg",
      cast_id: 114,
      character: "Agent Foster",
      credit_id: "682b9b95bee6ea1318db2e76",
      order: 13,
    },
    {
      adult: false,
      gender: 0,
      id: 3516911,
      known_for_department: "Acting",
      name: "Judy Nguyen",
      original_name: "Judy Nguyen",
      popularity: 0.2329,
      profile_path: "/eT5a2EDIBx8wuFAWLTbctIL5Sof.jpg",
      cast_id: 115,
      character: "Agent Huynh",
      credit_id: "682b9bb4df31bc3909f5600a",
      order: 14,
    },
    {
      adult: false,
      gender: 2,
      id: 2655218,
      known_for_department: "Acting",
      name: "Christian Yeung",
      original_name: "Christian Yeung",
      popularity: 1.1929,
      profile_path: null,
      cast_id: 116,
      character: "Agent Zhao",
      credit_id: "682b9bc1e19cab56120bd9f3",
      order: 15,
    },
    {
      adult: false,
      gender: 0,
      id: 2139797,
      known_for_department: "Acting",
      name: "Courtney Coleman",
      original_name: "Courtney Coleman",
      popularity: 0.1446,
      profile_path: null,
      cast_id: 117,
      character: "Concierge",
      credit_id: "682b9bd0cc1d65777d8c0cdb",
      order: 16,
    },
    {
      adult: false,
      gender: 1,
      id: 1718812,
      known_for_department: "Acting",
      name: "Christina Souza",
      original_name: "Christina Souza",
      popularity: 1.1629,
      profile_path: null,
      cast_id: 118,
      character: "Doctor Pereira",
      credit_id: "682b9be669ebea95582f7721",
      order: 17,
    },
    {
      adult: false,
      gender: 0,
      id: 5449279,
      known_for_department: "Acting",
      name: "Emery Ho‘okano-Briel",
      original_name: "Emery Ho‘okano-Briel",
      popularity: 0.1553,
      profile_path: null,
      cast_id: 119,
      character: "Mertle",
      credit_id: "682b9c0bdd4fa4dc7f2f77df",
      order: 18,
    },
    {
      adult: false,
      gender: 2,
      id: 208956,
      known_for_department: "Acting",
      name: "Justin Martin",
      original_name: "Justin Martin",
      popularity: 1.966,
      profile_path: "/2Al03iCqhjIogfP7j1VYUvoLvyI.jpg",
      cast_id: 120,
      character: "Mertle's Dad",
      credit_id: "682b9c21bdfecb719a8c0a29",
      order: 19,
    },
    {
      adult: false,
      gender: 1,
      id: 1764418,
      known_for_department: "Acting",
      name: "Isabelle Du",
      original_name: "Isabelle Du",
      popularity: 0.3979,
      profile_path: null,
      cast_id: 121,
      character: "Mertle's Mom",
      credit_id: "682b9c30989cf65c7edb2e21",
      order: 20,
    },
    {
      adult: false,
      gender: 0,
      id: 5449282,
      known_for_department: "Acting",
      name: "Elle Hipa",
      original_name: "Elle Hipa",
      popularity: 0.1217,
      profile_path: null,
      cast_id: 122,
      character: "Mertle's Friend #1",
      credit_id: "682b9c4629b78a28ca8c091a",
      order: 21,
    },
    {
      adult: false,
      gender: 0,
      id: 5449283,
      known_for_department: "Acting",
      name: "Arianna Jordan Ignacio Acidera",
      original_name: "Arianna Jordan Ignacio Acidera",
      popularity: 0.0814,
      profile_path: null,
      cast_id: 123,
      character: "Mertle's Friend #2",
      credit_id: "682b9c701454889f4b8c09d2",
      order: 22,
    },
    {
      adult: false,
      gender: 0,
      id: 5449284,
      known_for_department: "Acting",
      name: "Aubrey Rose Madarang",
      original_name: "Aubrey Rose Madarang",
      popularity: 0.0718,
      profile_path: null,
      cast_id: 124,
      character: "Mertle's Friend #3",
      credit_id: "682b9c80eeec5423d90bd9da",
      order: 23,
    },
    {
      adult: false,
      gender: 0,
      id: 2075101,
      known_for_department: "Acting",
      name: "Stephanie Lum",
      original_name: "Stephanie Lum",
      popularity: 0.1244,
      profile_path: null,
      cast_id: 125,
      character: "Local News Reporter",
      credit_id: "682b9c8fbdd07163dd2f764b",
      order: 24,
    },
    {
      adult: false,
      gender: 2,
      id: 1609238,
      known_for_department: "Acting",
      name: "Don Nahaku",
      original_name: "Don Nahaku",
      popularity: 1.4308,
      profile_path: null,
      cast_id: 126,
      character: "Mr. Agas",
      credit_id: "682b9c9d0fae87163af55ff3",
      order: 25,
    },
    {
      adult: false,
      gender: 1,
      id: 2848984,
      known_for_department: "Acting",
      name: "Tira Akina",
      original_name: "Tira Akina",
      popularity: 0.1344,
      profile_path: "/aio4XDQp8coWqZmSAIShVhSgiQ3.jpg",
      cast_id: 127,
      character: "Lū'au Employee",
      credit_id: "682b9caa989cf65c7edb2e29",
      order: 26,
    },
    {
      adult: false,
      gender: 0,
      id: 3960878,
      known_for_department: "Acting",
      name: "Suzanne Green",
      original_name: "Suzanne Green",
      popularity: 0.0434,
      profile_path: null,
      cast_id: 128,
      character: "Older Tourist",
      credit_id: "682b9cc129b78a28ca8c091f",
      order: 27,
    },
    {
      adult: false,
      gender: 0,
      id: 5449287,
      known_for_department: "Acting",
      name: "Diana Curammeng Seppelfrick",
      original_name: "Diana Curammeng Seppelfrick",
      popularity: 0.0239,
      profile_path: null,
      cast_id: 129,
      character: "Veteran Cleaning Lady",
      credit_id: "682b9cd2bdd07163dd2f7657",
      order: 28,
    },
    {
      adult: false,
      gender: 0,
      id: 4345251,
      known_for_department: "Acting",
      name: "Esera Tuaolo",
      original_name: "Esera Tuaolo",
      popularity: 0.3633,
      profile_path: null,
      cast_id: 130,
      character: "Janitor",
      credit_id: "682b9cea15a01d5a44e2500c",
      order: 29,
    },
    {
      adult: false,
      gender: 2,
      id: 4775908,
      known_for_department: "Acting",
      name: "Hualālai Chung",
      original_name: "Hualālai Chung",
      popularity: 0.4618,
      profile_path: "/x2g5fdHqETY9dZgL4aB0QDP0boR.jpg",
      cast_id: 131,
      character: "Animal Control Worker #1",
      credit_id: "682b9cf8989cf65c7edb2e32",
      order: 30,
    },
    {
      adult: false,
      gender: 0,
      id: 5136046,
      known_for_department: "Acting",
      name: "Mason Manuma",
      original_name: "Mason Manuma",
      popularity: 0.0357,
      profile_path: null,
      cast_id: 132,
      character: "Animal Control Worker #2",
      credit_id: "682b9d06d695b950850bda18",
      order: 31,
    },
    {
      adult: false,
      gender: 2,
      id: 2568565,
      known_for_department: "Acting",
      name: "Alex Denney",
      original_name: "Alex Denney",
      popularity: 0.246,
      profile_path: "/3mi2wXzrZCHfYk7vSdmjWf3Jjqk.jpg",
      cast_id: 133,
      character: "Best Man",
      credit_id: "682b9d173b42329f998c0a2e",
      order: 32,
    },
    {
      adult: false,
      gender: 2,
      id: 2139812,
      known_for_department: "Acting",
      name: "David Hekili Kenui Bell",
      original_name: "David Hekili Kenui Bell",
      popularity: 0.1476,
      profile_path: null,
      cast_id: 169,
      character: "Big Hawaiian Dude",
      credit_id: "682d64f2bb2a3d77b7f566f1",
      order: 33,
    },
    {
      adult: false,
      gender: 2,
      id: 1336796,
      known_for_department: "Acting",
      name: "Mike Mitchell",
      original_name: "Mike Mitchell",
      popularity: 1.9591,
      profile_path: "/fwn7cNiVmfGAOvbH2auqgSFVixn.jpg",
      cast_id: 135,
      character: "Hammerhead Guard",
      credit_id: "682b9d4f701b4093605b5dba",
      order: 34,
    },
    {
      adult: false,
      gender: 1,
      id: 1561797,
      known_for_department: "Production",
      name: "Ashley Lambert",
      original_name: "Ashley Lambert",
      popularity: 2.3629,
      profile_path: "/ucsdNz1pdVWwRFwf4dtjfaXE8nR.jpg",
      cast_id: 137,
      character: "Ship Voice (voice)",
      credit_id: "682b9d822fe2fc11aa9e3883",
      order: 35,
    },
    {
      adult: false,
      gender: 0,
      id: 5449938,
      known_for_department: "Acting",
      name: "Lyanna Miyashiro",
      original_name: "Lyanna Miyashiro",
      popularity: 0.0362,
      profile_path: null,
      cast_id: 138,
      character: "Hula Dancer",
      credit_id: "682d626903dc7f4ef2db34dc",
      order: 36,
    },
    {
      adult: false,
      gender: 0,
      id: 5449941,
      known_for_department: "Acting",
      name: "Raeyah Ibana-Tago",
      original_name: "Raeyah Ibana-Tago",
      popularity: 0.0336,
      profile_path: null,
      cast_id: 139,
      character: "Hula Dancer",
      credit_id: "682d62758de1323ad8db33ee",
      order: 37,
    },
    {
      adult: false,
      gender: 0,
      id: 5449943,
      known_for_department: "Acting",
      name: "Drew Naone",
      original_name: "Drew Naone",
      popularity: 0.0453,
      profile_path: null,
      cast_id: 140,
      character: "Hula Dancer",
      credit_id: "682d6282da70b514d6f5670f",
      order: 38,
    },
    {
      adult: false,
      gender: 0,
      id: 5449945,
      known_for_department: "Acting",
      name: "Jessica Makua",
      original_name: "Jessica Makua",
      popularity: 0.052,
      profile_path: null,
      cast_id: 141,
      character: "Hula Dancer",
      credit_id: "682d628a7e07d6ffec9e407a",
      order: 39,
    },
    {
      adult: false,
      gender: 0,
      id: 5449946,
      known_for_department: "Acting",
      name: "Tiani Scott",
      original_name: "Tiani Scott",
      popularity: 0.0239,
      profile_path: null,
      cast_id: 142,
      character: "Hula Dancer",
      credit_id: "682d62943bf1467c07db3744",
      order: 40,
    },
    {
      adult: false,
      gender: 0,
      id: 5449950,
      known_for_department: "Acting",
      name: "Moanike‘ala Scott",
      original_name: "Moanike‘ala Scott",
      popularity: 0.0143,
      profile_path: null,
      cast_id: 143,
      character: "Hula Dancer",
      credit_id: "682d629c5f05a71dd42f7f4f",
      order: 41,
    },
    {
      adult: false,
      gender: 0,
      id: 5449952,
      known_for_department: "Acting",
      name: "Chez Napualani Panui",
      original_name: "Chez Napualani Panui",
      popularity: 0.0362,
      profile_path: null,
      cast_id: 144,
      character: "Hula Dancer",
      credit_id: "682d62a34321d6b1069e4005",
      order: 42,
    },
    {
      adult: false,
      gender: 0,
      id: 5449954,
      known_for_department: "Acting",
      name: "Sapati Laloulu",
      original_name: "Sapati Laloulu",
      popularity: 0.0214,
      profile_path: null,
      cast_id: 145,
      character: "Fire Knife Dancer",
      credit_id: "682d62b003dc7f4ef2db34e3",
      order: 43,
    },
    {
      adult: false,
      gender: 0,
      id: 5449956,
      known_for_department: "Acting",
      name: "Achiles Tafiti",
      original_name: "Achiles Tafiti",
      popularity: 0.0143,
      profile_path: null,
      cast_id: 146,
      character: "Fire Knife Dancer",
      credit_id: "682d62b7bdfecb719a8c13c1",
      order: 44,
    },
    {
      adult: false,
      gender: 1,
      id: 1382071,
      known_for_department: "Acting",
      name: "Elizabeth Peterson",
      original_name: "Elizabeth Peterson",
      popularity: 0.2128,
      profile_path: "/lmxq320qLjyVaALnBqSrd9mIjXd.jpg",
      cast_id: 147,
      character: "Tahitian Dancer",
      credit_id: "682d62d5f5ca8ac4a62f13ef",
      order: 45,
    },
    {
      adult: false,
      gender: 0,
      id: 5452263,
      known_for_department: "Acting",
      name: "Celeste Mosqueda",
      original_name: "Celeste Mosqueda",
      popularity: 0.0143,
      profile_path: null,
      cast_id: 148,
      character: "Tahitian Dancer",
      credit_id: "682d62fb9c392c1e61f566ed",
      order: 46,
    },
    {
      adult: false,
      gender: 0,
      id: 2832866,
      known_for_department: "Acting",
      name: "Sacha Lee",
      original_name: "Sacha Lee",
      popularity: 0.0497,
      profile_path: null,
      cast_id: 149,
      character: "Tahitian Dancer",
      credit_id: "682d6308363fe5d2f6e2552e",
      order: 47,
    },
    {
      adult: false,
      gender: 0,
      id: 5452264,
      known_for_department: "Acting",
      name: "Jasmin Ella Mercado Domingo",
      original_name: "Jasmin Ella Mercado Domingo",
      popularity: 0.0143,
      profile_path: null,
      cast_id: 150,
      character: "Tahitian Dancer",
      credit_id: "682d631bf5a4f4eac80be19f",
      order: 48,
    },
    {
      adult: false,
      gender: 0,
      id: 5452266,
      known_for_department: "Acting",
      name: "Cassandra Kahoku'imo'imo Ainoa-Kanoho",
      original_name: "Cassandra Kahoku'imo'imo Ainoa-Kanoho",
      popularity: 0.0362,
      profile_path: null,
      cast_id: 151,
      character: "Tahitian Dancer",
      credit_id: "682d633d010214cda59e42d5",
      order: 49,
    },
    {
      adult: false,
      gender: 0,
      id: 5452267,
      known_for_department: "Acting",
      name: "Naomi Baldomero",
      original_name: "Naomi Baldomero",
      popularity: 0.0168,
      profile_path: null,
      cast_id: 152,
      character: "Tahitian Dancer",
      credit_id: "682d634c5613abdd990be338",
      order: 50,
    },
    {
      adult: false,
      gender: 0,
      id: 5452269,
      known_for_department: "Acting",
      name: "Chansen Exzabe",
      original_name: "Chansen Exzabe",
      popularity: 0.0143,
      profile_path: null,
      cast_id: 153,
      character: "Lū'au Drummer",
      credit_id: "682d636c5613abdd990be343",
      order: 51,
    },
    {
      adult: false,
      gender: 0,
      id: 5452270,
      known_for_department: "Acting",
      name: "Heinere Itchner",
      original_name: "Heinere Itchner",
      popularity: 0.0214,
      profile_path: null,
      cast_id: 154,
      character: "Lū'au Drummer",
      credit_id: "682d63829ca17c9182649972",
      order: 52,
    },
    {
      adult: false,
      gender: 0,
      id: 5452271,
      known_for_department: "Acting",
      name: "Jesus Kawaiaea-Benitez",
      original_name: "Jesus Kawaiaea-Benitez",
      popularity: 0.0286,
      profile_path: null,
      cast_id: 155,
      character: "Lū'au Drummer",
      credit_id: "682d6397f5604cf01e9e3ffc",
      order: 53,
    },
    {
      adult: false,
      gender: 0,
      id: 5452273,
      known_for_department: "Acting",
      name: "Charles Temanaha",
      original_name: "Charles Temanaha",
      popularity: 0.0214,
      profile_path: null,
      cast_id: 156,
      character: "Lū'au Drummer",
      credit_id: "682d63a5a85a6f01e4db31d6",
      order: 54,
    },
    {
      adult: false,
      gender: 0,
      id: 5452274,
      known_for_department: "Acting",
      name: "Tyrone Temanaha",
      original_name: "Tyrone Temanaha",
      popularity: 0.0264,
      profile_path: null,
      cast_id: 157,
      character: "Lū'au Drummer",
      credit_id: "682d63ae989cf65c7edb363f",
      order: 55,
    },
    {
      adult: false,
      gender: 0,
      id: 5452275,
      known_for_department: "Acting",
      name: "Leigh Uta",
      original_name: "Leigh Uta",
      popularity: 0.0239,
      profile_path: null,
      cast_id: 158,
      character: "Lū'au Drummer",
      credit_id: "682d63b6989cf65c7edb364a",
      order: 56,
    },
    {
      adult: false,
      gender: 0,
      id: 5452276,
      known_for_department: "Acting",
      name: "Kanoa Kalā Kelaoha",
      original_name: "Kanoa Kalā Kelaoha",
      popularity: 0.0261,
      profile_path: null,
      cast_id: 159,
      character: "Hula Drummers",
      credit_id: "682d63d08de1323ad8db340d",
      order: 57,
    },
    {
      adult: false,
      gender: 0,
      id: 5452277,
      known_for_department: "Acting",
      name: "Rudy Kapono Gaco",
      original_name: "Rudy Kapono Gaco",
      popularity: 0.0286,
      profile_path: null,
      cast_id: 160,
      character: "Hula Drummers",
      credit_id: "682d63da7f67ac825a2f1333",
      order: 58,
    },
    {
      adult: false,
      gender: 0,
      id: 5424199,
      known_for_department: "Acting",
      name: "Dane Drewis",
      original_name: "Dane Drewis",
      popularity: 0.0261,
      profile_path: null,
      cast_id: 161,
      character: "Coffee Shop Owner",
      credit_id: "682d63e764ff813d3b9e3df8",
      order: 59,
    },
    {
      adult: false,
      gender: 0,
      id: 1541239,
      known_for_department: "Acting",
      name: "Nolan Hong",
      original_name: "Nolan Hong",
      popularity: 0.1988,
      profile_path: "/fUrOK5S2cC4wfJuNQ56OOXlSvW4.jpg",
      cast_id: 162,
      character: "Emcee",
      credit_id: "682d6415a58c5098532f7eec",
      order: 60,
    },
    {
      adult: false,
      gender: 0,
      id: 2213348,
      known_for_department: "Acting",
      name: "Brandon Toma",
      original_name: "Brandon Toma",
      popularity: 0.0994,
      profile_path: null,
      cast_id: 163,
      character: "Cop",
      credit_id: "682d641d5d142a60730be1d2",
      order: 61,
    },
    {
      adult: false,
      gender: 2,
      id: 188694,
      known_for_department: "Acting",
      name: "Mark Beltzman",
      original_name: "Mark Beltzman",
      popularity: 0.9943,
      profile_path: "/97oUiYEjKWdATDRDvJvL3Lug4qo.jpg",
      cast_id: 164,
      character: "Hot Tub Guy",
      credit_id: "682d6424cc1d65777d8c135b",
      order: 62,
    },
    {
      adult: false,
      gender: 0,
      id: 5452279,
      known_for_department: "Acting",
      name: "Tumua Tuinei",
      original_name: "Tumua Tuinei",
      popularity: 0.0214,
      profile_path: null,
      cast_id: 165,
      character: "Riti",
      credit_id: "682d643dc5a5bb50540be282",
      order: 63,
    },
    {
      adult: false,
      gender: 0,
      id: 5452281,
      known_for_department: "Acting",
      name: "Stephen Hadhazi",
      original_name: "Stephen Hadhazi",
      popularity: 0.0143,
      profile_path: null,
      cast_id: 166,
      character: "Rude Guy",
      credit_id: "682d6464de6c434d038c10be",
      order: 64,
    },
    {
      adult: false,
      gender: 0,
      id: 5452282,
      known_for_department: "Acting",
      name: "Genesis Molina",
      original_name: "Genesis Molina",
      popularity: 0.0143,
      profile_path: null,
      cast_id: 167,
      character: "Pleakley Proxy",
      credit_id: "682d64742a7ca4b1958c10d8",
      order: 65,
    },
    {
      adult: false,
      gender: 0,
      id: 5452283,
      known_for_department: "Acting",
      name: "Alexander David Johnson",
      original_name: "Alexander David Johnson",
      popularity: 0.0264,
      profile_path: null,
      cast_id: 168,
      character: "Pleakley Proxy #2",
      credit_id: "682d6484fa571899e42f13c8",
      order: 66,
    },
    {
      adult: false,
      gender: 0,
      id: 5458101,
      known_for_department: "Acting",
      name: "Justin Martin",
      original_name: "Justin Martin",
      popularity: 0.0214,
      profile_path: null,
      cast_id: 174,
      character: "Mertle's Dad",
      credit_id: "6830f36574bf8ae53f2b6654",
      order: 67,
    },
    {
      adult: false,
      gender: 0,
      id: 4360832,
      known_for_department: "Acting",
      name: "Charles Gould",
      original_name: "Charles Gould",
      popularity: 0.1405,
      profile_path: null,
      cast_id: 175,
      character: "Hulu Dancer / Stitch Boy",
      credit_id: "68377b03155bf9d935838c11",
      order: 68,
    },
  ],
  crew: [
    {
      adult: false,
      gender: 0,
      id: 1686000,
      known_for_department: "Production",
      name: "Ryan Halprin",
      original_name: "Ryan Halprin",
      popularity: 0.3992,
      profile_path: null,
      credit_id: "62d073312d8ef300c2e39a25",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      gender: 2,
      id: 1540069,
      known_for_department: "Directing",
      name: "Dean Fleischer Camp",
      original_name: "Dean Fleischer Camp",
      popularity: 2.9314,
      profile_path: "/oZTIL77jVfcz8iEQnYC892jvqY3.jpg",
      credit_id: "62d0730f0b5fd6005387f489",
      department: "Directing",
      job: "Director",
    },
    {
      adult: false,
      gender: 0,
      id: 1167490,
      known_for_department: "Art",
      name: "Anne Costa",
      original_name: "Anne Costa",
      popularity: 0.8813,
      profile_path: null,
      credit_id: "6568221e09c24c00c45893b3",
      department: "Art",
      job: "Art Direction",
    },
    {
      adult: false,
      gender: 0,
      id: 2664737,
      known_for_department: "Production",
      name: "Angran Li",
      original_name: "Angran Li",
      popularity: 0.306,
      profile_path: null,
      credit_id: "6568222be1ad79014d4c21e2",
      department: "Art",
      job: "Art Direction",
    },
    {
      adult: false,
      gender: 0,
      id: 3160998,
      known_for_department: "Art",
      name: "Katrin Chong",
      original_name: "Katrin Chong",
      popularity: 0.5594,
      profile_path: null,
      credit_id: "6568224be1ad7900c9eeb262",
      department: "Art",
      job: "Set Decoration",
    },
    {
      adult: false,
      gender: 1,
      id: 35514,
      known_for_department: "Costume & Make-Up",
      name: "Wendy Chuck",
      original_name: "Wendy Chuck",
      popularity: 1.4901,
      profile_path: "/oe2F9wVKMqnFGQyEedJ9GjAO1cm.jpg",
      credit_id: "6568225ae1ad7900c9eeb26b",
      department: "Costume & Make-Up",
      job: "Costume Design",
    },
    {
      adult: false,
      gender: 2,
      id: 959555,
      known_for_department: "Art",
      name: "Todd Cherniawsky",
      original_name: "Todd Cherniawsky",
      popularity: 1.9507,
      profile_path: null,
      credit_id: "6568220109c24c00acfdca69",
      department: "Art",
      job: "Production Design",
    },
    {
      adult: false,
      gender: 0,
      id: 1683361,
      known_for_department: "Art",
      name: "Julien Pougnier",
      original_name: "Julien Pougnier",
      popularity: 2.1792,
      profile_path: null,
      credit_id: "65682237fb5299013c50c7f2",
      department: "Art",
      job: "Supervising Art Director",
    },
    {
      adult: false,
      gender: 2,
      id: 3624081,
      known_for_department: "Writing",
      name: "Chris Kekaniokalani Bright",
      original_name: "Chris Kekaniokalani Bright",
      popularity: 1.0482,
      profile_path: "/d6fjYERnz6VPyxtp1cm0HMkLyoW.jpg",
      credit_id: "63f000594a4bfc0096374d85",
      department: "Writing",
      job: "Screenplay",
    },
    {
      adult: false,
      gender: 2,
      id: 76845,
      known_for_department: "Camera",
      name: "Nigel Bluck",
      original_name: "Nigel Bluck",
      popularity: 0.5805,
      profile_path: null,
      credit_id: "64a0405e8c0a48013b3d2fa4",
      department: "Camera",
      job: "Director of Photography",
    },
    {
      adult: false,
      gender: 0,
      id: 1102209,
      known_for_department: "Production",
      name: "Tom C. Peitzman",
      original_name: "Tom C. Peitzman",
      popularity: 1.7669,
      profile_path: null,
      credit_id: "66b725921d694ae016a7b42a",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      gender: 2,
      id: 1853076,
      known_for_department: "Production",
      name: "Jonathan Eirich",
      original_name: "Jonathan Eirich",
      popularity: 0.8588,
      profile_path: "/aY7jRYOb2jMlctQkknh0vpSC79y.jpg",
      credit_id: "5bb9343b9251417f4900e86d",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      gender: 2,
      id: 112690,
      known_for_department: "Production",
      name: "Dan Lin",
      original_name: "Dan Lin",
      popularity: 1.3775,
      profile_path: "/skXxQ2MZ2OYpP0aFyBoieFTT3iK.jpg",
      credit_id: "5bb934269251410a24016440",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      gender: 2,
      id: 1484209,
      known_for_department: "Visual Effects",
      name: "Craig Hammack",
      original_name: "Craig Hammack",
      popularity: 2.5713,
      profile_path: "/yMyaQDw1sdsjqLVGUBdj8rjEUZ6.jpg",
      credit_id: "6712e7761f0ea4714edc32cf",
      department: "Visual Effects",
      job: "Visual Effects Supervisor",
    },
    {
      adult: false,
      gender: 0,
      id: 2762717,
      known_for_department: "Visual Effects",
      name: "Will Reichelt",
      original_name: "Will Reichelt",
      popularity: 0.2922,
      profile_path: null,
      credit_id: "6712e78398f6a758cd54eadf",
      department: "Visual Effects",
      job: "Visual Effects Supervisor",
    },
    {
      adult: false,
      gender: 0,
      id: 1470162,
      known_for_department: "Visual Effects",
      name: "Bruno Baron",
      original_name: "Bruno Baron",
      popularity: 0.3601,
      profile_path: null,
      credit_id: "6712e7928e844657b7fb566d",
      department: "Visual Effects",
      job: "Visual Effects Supervisor",
    },
    {
      adult: false,
      gender: 0,
      id: 5008770,
      known_for_department: "Visual Effects",
      name: "Matthew Shumway",
      original_name: "Matthew Shumway",
      popularity: 0.201,
      profile_path: null,
      credit_id: "6712e7b925c70b8b1d67f0b4",
      department: "Visual Effects",
      job: "Animation Supervisor",
    },
    {
      adult: false,
      gender: 0,
      id: 3131178,
      known_for_department: "Visual Effects",
      name: "Christopher Marshall",
      original_name: "Christopher Marshall",
      popularity: 0.0835,
      profile_path: null,
      credit_id: "6712e7dd1f0ea4714edc32dd",
      department: "Visual Effects",
      job: "Animation Supervisor",
    },
    {
      adult: false,
      gender: 0,
      id: 1729044,
      known_for_department: "Visual Effects",
      name: "Lauren Fong",
      original_name: "Lauren Fong",
      popularity: 0.2513,
      profile_path: null,
      credit_id: "6712e8071f0ea4714edc32f5",
      department: "Visual Effects",
      job: "Visual Effects Producer",
    },
    {
      adult: false,
      gender: 2,
      id: 66193,
      known_for_department: "Directing",
      name: "Chris Sanders",
      original_name: "Chris Sanders",
      popularity: 5.2782,
      profile_path: "/6CtrIOCxggJ5eIAWeFQqd4Hs9FP.jpg",
      credit_id: "674e38d4d27dcf00523f311c",
      department: "Writing",
      job: "Original Film Writer",
    },
    {
      adult: false,
      gender: 2,
      id: 69797,
      known_for_department: "Directing",
      name: "Dean DeBlois",
      original_name: "Dean DeBlois",
      popularity: 2.9159,
      profile_path: "/cgdyNSkltPMtWDdKkFP0d4W361v.jpg",
      credit_id: "674e38e7aa4c1e2413a1dfbb",
      department: "Writing",
      job: "Original Film Writer",
    },
    {
      adult: false,
      gender: 0,
      id: 1395438,
      known_for_department: "Art",
      name: "Val Drake",
      original_name: "Val Drake",
      popularity: 1.1302,
      profile_path: null,
      credit_id: "676455555883585afba4fa2f",
      department: "Art",
      job: "Sculptor",
    },
    {
      adult: false,
      gender: 0,
      id: 1423746,
      known_for_department: "Costume & Make-Up",
      name: "Maria Sandoval",
      original_name: "Maria Sandoval",
      popularity: 0.277,
      profile_path: null,
      credit_id: "676df91ccfe62644df12a8be",
      department: "Costume & Make-Up",
      job: "Hair Department Head",
    },
    {
      adult: false,
      gender: 2,
      id: 1787802,
      known_for_department: "Directing",
      name: "Brian Avery Galligan",
      original_name: "Brian Avery Galligan",
      popularity: 1.8533,
      profile_path: null,
      credit_id: "676df935cfe62644df12a8cc",
      department: "Directing",
      job: "First Assistant Director",
    },
    {
      adult: false,
      gender: 2,
      id: 182213,
      known_for_department: "Crew",
      name: "Marcus Young",
      original_name: "Marcus Young",
      popularity: 0.3056,
      profile_path: "/txBvkZc6W5uTDbFeiMJ9sOPyUof.jpg",
      credit_id: "676dfa3c0c4402b631928d59",
      department: "Crew",
      job: "Stunt Coordinator",
    },
    {
      adult: false,
      gender: 2,
      id: 1155140,
      known_for_department: "Sound",
      name: "Dan Romer",
      original_name: "Dan Romer",
      popularity: 1.4588,
      profile_path: "/cOoq9WBHzuZ3L3BmPvUBiB7c67x.jpg",
      credit_id: "67a96ef20bf46f8e880f7332",
      department: "Sound",
      job: "Original Music Composer",
    },
    {
      adult: false,
      gender: 2,
      id: 15894,
      known_for_department: "Sound",
      name: "Tom Myers",
      original_name: "Tom Myers",
      popularity: 2.4082,
      profile_path: "/igQ5idVJbKHFHaUPvIyR40qiZyF.jpg",
      credit_id: "67b747be0c61025fafc41c48",
      department: "Sound",
      job: "Sound Designer",
    },
    {
      adult: false,
      gender: 2,
      id: 15894,
      known_for_department: "Sound",
      name: "Tom Myers",
      original_name: "Tom Myers",
      popularity: 2.4082,
      profile_path: "/igQ5idVJbKHFHaUPvIyR40qiZyF.jpg",
      credit_id: "67b747d4e484fc21541a2431",
      department: "Sound",
      job: "Supervising Sound Editor",
    },
    {
      adult: false,
      gender: 2,
      id: 15894,
      known_for_department: "Sound",
      name: "Tom Myers",
      original_name: "Tom Myers",
      popularity: 2.4082,
      profile_path: "/igQ5idVJbKHFHaUPvIyR40qiZyF.jpg",
      credit_id: "67b748030c61025fafc41c92",
      department: "Sound",
      job: "Sound Re-Recording Mixer",
    },
    {
      adult: false,
      gender: 2,
      id: 1412985,
      known_for_department: "Sound",
      name: "Andre Fenley",
      original_name: "Andre Fenley",
      popularity: 1.1812,
      profile_path: null,
      credit_id: "67b748250c61025fafc41cc6",
      department: "Sound",
      job: "Supervising Sound Editor",
    },
    {
      adult: false,
      gender: 2,
      id: 138618,
      known_for_department: "Sound",
      name: "Gary Rizzo",
      original_name: "Gary Rizzo",
      popularity: 4.0563,
      profile_path: "/m8vT9fYRLwM8WPpJiq8QIMBSueQ.jpg",
      credit_id: "67b748360c61025fafc41cd5",
      department: "Sound",
      job: "Sound Re-Recording Mixer",
    },
    {
      adult: false,
      gender: 2,
      id: 2032020,
      known_for_department: "Writing",
      name: "Mike Van Waes",
      original_name: "Mike Van Waes",
      popularity: 1.4455,
      profile_path: "/cb4zKWuV4rbMD5cGd50kcJeIMt.jpg",
      credit_id: "67d076efd4f7413732607139",
      department: "Writing",
      job: "Screenplay",
    },
    {
      adult: false,
      gender: 2,
      id: 1001719,
      known_for_department: "Editing",
      name: "Phillip J. Bartell",
      original_name: "Phillip J. Bartell",
      popularity: 1.9961,
      profile_path: "/bO3gIu9SnGqMp70xtSjsaCVQdjT.jpg",
      credit_id: "67d31a99cfc4565c211dcde4",
      department: "Editing",
      job: "Editor",
    },
    {
      adult: false,
      gender: 1,
      id: 1450292,
      known_for_department: "Production",
      name: "Leigh Shanta",
      original_name: "Leigh Shanta",
      popularity: 0.8546,
      profile_path: null,
      credit_id: "67d31acba97c646cb5813e09",
      department: "Production",
      job: "Unit Production Manager",
    },
    {
      adult: false,
      gender: 1,
      id: 1027021,
      known_for_department: "Directing",
      name: "Stephanie Tull",
      original_name: "Stephanie Tull",
      popularity: 0.8478,
      profile_path: null,
      credit_id: "67d31afc067c4ca7b0607f16",
      department: "Directing",
      job: "Second Assistant Director",
    },
    {
      adult: false,
      gender: 0,
      id: 1745942,
      known_for_department: "Directing",
      name: "Richard Oswald",
      original_name: "Richard Oswald",
      popularity: 1.9598,
      profile_path: null,
      credit_id: "67d31b2c66892bad6281bcf0",
      department: "Directing",
      job: "Second Assistant Director",
    },
    {
      adult: false,
      gender: 2,
      id: 6187,
      known_for_department: "Production",
      name: "Aldric La'Auli Porter",
      original_name: "Aldric La'Auli Porter",
      popularity: 2.2225,
      profile_path: null,
      credit_id: "67d31b3f66892bad6281bd03",
      department: "Directing",
      job: "First Assistant Director",
    },
    {
      adult: false,
      gender: 0,
      id: 2897082,
      known_for_department: "Directing",
      name: "Kate Pulley",
      original_name: "Kate Pulley",
      popularity: 0.3794,
      profile_path: null,
      credit_id: "67d31b4b434c98c8ec81ccfe",
      department: "Directing",
      job: "Second Assistant Director",
    },
    {
      adult: false,
      gender: 0,
      id: 5302580,
      known_for_department: "Crew",
      name: "Shannon Thorp",
      original_name: "Shannon Thorp",
      popularity: 0.1428,
      profile_path: null,
      credit_id: "67d31b56434c98c8ec81cd0c",
      department: "Crew",
      job: "Set Production Assistant",
    },
    {
      adult: false,
      gender: 2,
      id: 1412481,
      known_for_department: "Art",
      name: "Colin Bach",
      original_name: "Colin Bach",
      popularity: 0.5632,
      profile_path: null,
      credit_id: "67d31b672575f01b3a60a99a",
      department: "Art",
      job: "Assistant Property Master",
    },
    {
      adult: false,
      gender: 2,
      id: 1450350,
      known_for_department: "Writing",
      name: "Heiko von Drengenberg",
      original_name: "Heiko von Drengenberg",
      popularity: 0.6696,
      profile_path: null,
      credit_id: "67d31b9ce188eaa47c1de909",
      department: "Art",
      job: "Storyboard Artist",
    },
    {
      adult: false,
      gender: 2,
      id: 1763798,
      known_for_department: "Editing",
      name: "Alex Bickel",
      original_name: "Alex Bickel",
      popularity: 2.5101,
      profile_path: null,
      credit_id: "67d31bcad4f741373260ee23",
      department: "Editing",
      job: "Colorist",
    },
    {
      adult: false,
      gender: 2,
      id: 1400535,
      known_for_department: "Camera",
      name: "Colin Anderson",
      original_name: "Colin Anderson",
      popularity: 2.0195,
      profile_path: null,
      credit_id: "67e59a14e8a1910e6510c40c",
      department: "Camera",
      job: '"A" Camera Operator',
    },
    {
      adult: false,
      gender: 0,
      id: 1463450,
      known_for_department: "Visual Effects",
      name: "Jason Billington",
      original_name: "Jason Billington",
      popularity: 0.9363,
      profile_path: null,
      credit_id: "68100d54a90acaf6eeeaf014",
      department: "Visual Effects",
      job: "Visual Effects Supervisor",
    },
    {
      adult: false,
      gender: 2,
      id: 1571982,
      known_for_department: "Visual Effects",
      name: "Rupert Davies",
      original_name: "Rupert Davies",
      popularity: 0.6784,
      profile_path: null,
      credit_id: "68100d5f4603571ead0faee3",
      department: "Visual Effects",
      job: "Visual Effects Supervisor",
    },
    {
      adult: false,
      gender: 0,
      id: 1788085,
      known_for_department: "Production",
      name: "Louie Provost",
      original_name: "Louie Provost",
      popularity: 0.1177,
      profile_path: null,
      credit_id: "681c1ca49084164184b1c65b",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 1492646,
      known_for_department: "Production",
      name: "Sande Alessi",
      original_name: "Sande Alessi",
      popularity: 2.083,
      profile_path: null,
      credit_id: "681c1d23b541a7cb1f01e6c6",
      department: "Production",
      job: "Extras Casting",
    },
    {
      adult: false,
      gender: 2,
      id: 1445838,
      known_for_department: "Sound",
      name: "Leff Lefferts",
      original_name: "Leff Lefferts",
      popularity: 1.6967,
      profile_path: null,
      credit_id: "681d09ac8db02473f293afe9",
      department: "Sound",
      job: "Sound Effects Editor",
    },
    {
      adult: false,
      gender: 0,
      id: 5452290,
      known_for_department: "Art",
      name: "Julienne De Rose Souchon",
      original_name: "Julienne De Rose Souchon",
      popularity: 0.0143,
      profile_path: null,
      credit_id: "682d65c8989cf65c7edb365a",
      department: "Art",
      job: "Set Dresser",
    },
    {
      adult: false,
      gender: 2,
      id: 6187,
      known_for_department: "Production",
      name: "Aldric La'Auli Porter",
      original_name: "Aldric La'Auli Porter",
      popularity: 2.2225,
      profile_path: null,
      credit_id: "682d665f2fe2fc11aa9e406a",
      department: "Production",
      job: "Co-Producer",
    },
    {
      adult: false,
      gender: 2,
      id: 122609,
      known_for_department: "Production",
      name: "Thomas Schumacher",
      original_name: "Thomas Schumacher",
      popularity: 2.1597,
      profile_path: "/xlQA0rqftYvFxIhU3J7NXm7FRoJ.jpg",
      credit_id: "682d66d1a788f78d88649578",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 2025225,
      known_for_department: "Visual Effects",
      name: "Gem Ronn Cadiz",
      original_name: "Gem Ronn Cadiz",
      popularity: 2.2062,
      profile_path: null,
      credit_id: "682d67d35211a914f28c100d",
      department: "Visual Effects",
      job: "VFX Artist",
    },
  ],
};
